services:
  mongo:
    image: mongo:8
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: songs
    ports:
    - "27017:27017"
    healthcheck:
      test: ["CMD", "mongo", "--username", "user", "--password", "password", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
    - mongo-data:/data/db

volumes:
  mongo-data: